### ISSUE TITLE
Minimize IP overlap?

### ISSUE THREAD

**Issue by xAvarice** [znetstar/tor-router#7]
I want a separate instance or ip for several "users" and I want to avoid the ips overlapping for each set of requests as much as possible... however I read requests using this router are sent in a "round robin" fashion?

Is this possible using this library?

**Comment by znetstar** [comment]
Hey xAvarice, I'm working on a feature with would allow you to connect to a specific instance identified by the username used when connecting to the proxy. For example, if you created an instance called "instance-1" and connected to "socks5://instance-1:@localhost:9050" all requests would be routed to "instance-1". It would also work for the http proxy but not DNS proxy since DNS doesn't support authentication. 

I'll have it up in the coming days.

**Comment by znetstar** [comment]
I can easily extend that to groups of instances. Which is what I think you're looking for.

**Comment by znetstar** [comment]
Featured added. See https://github.com/znetstar/tor-router#groups
